source 'https://rubygems.org'

gem 'sinatra'
gem 'shotgun'
gem 'nokogiri'
gem 'daybreak'
gem 'faraday'
gem 'byebug'
gem 'dotenv'
gem 'geocoder'
gem 'hashie'
gem 'childprocess'

gem 'weathercom', path: '/home/me/apps/wc'
